### ISSUE TITLE
Online Examples have errors

### ISSUE THREAD

**Issue by mcMunich** [ansys/pyworkbench-examples#101]
### 🔍 Before submitting the issue

- [x] I have searched among the existing issues
- [x] I am using a Python virtual environment

### 🐞 Description of the bug

This problem is related only to the online examples. Every one I have looked at shows errors.

![Image](https://github.com/user-attachments/assets/b6e9a486-2119-4dc8-85ec-1e0ef4547da6)

### 📝 Steps to reproduce

Open any of the examples. 

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

242

### 🐍 Which Python version are you using?

3.12

### 📦 Installed packages

NA

**Comment by franknli** [comment]
@mcMunich The "module not found" error indicate missing module. Did you install PyWorkbench package? And how did you install it?

**Comment by AnSergioFern** [comment]
Hey @franknli, @mcMunich is referring to the online documentation itself, for example at https://examples.workbench.docs.pyansys.com/version/dev/examples/logging/main.html

Unless you go back on to stable version 0.4 the documentation shows several "module nor found" errors.

**Comment by franknli** [comment]
> Hey [@franknli](https://github.com/franknli), [@mcMunich](https://github.com/mcMunich) is referring to the online documentation itself, for example at https://examples.workbench.docs.pyansys.com/version/dev/examples/logging/main.html
> 
> Unless you go back on to version 0.4 the documentation shows several "module not found" errors.

I see - thanks for the clarification.

@Revathyvenugopal162 So these python sessions in the documentation were live runs?

**Comment by jgd10** [comment]
If this library is like the other PyAnsys libraries (and I don't see why it wouldn't be), then whenever the project is built through CI/CD the examples are generated by being explicitly run using the newly built library. This checks that they are indeed working before being published, except that this bug shows that they aren't working.

So there are two things wrong here:

1. There is something wrong in the build step that means the examples are failing. I would guess there's been a syntax change recently or maybe the virtual environment is being set up incorrectly, but it's hard to say.
2. Even though the examples are failing the build is still being greenlit as OK to publish.

**Comment by jorgepiloto** [comment]
PyWorkbench dependency was commented out for some reason, see https://github.com/ansys/pyworkbench-examples/blob/53c1571c447b46648b4e3f6cab9691a192a79085/requirements/requirements_examples.txt#L1

This should be restored. Otherwise, the library is not being installed and the examples are not running.
